# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ndveye
                                 A QGIS plugin
 Plant counter.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-25
        copyright            : (C) 2024 by Bator Menyhert Koncz, Pal Szabo & Mona Dierickx
        email                : ndveye@protonmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Bator Menyhert Koncz, Pal Szabo & Mona Dierickx'
__date__ = '2024-03-25'
__copyright__ = '(C) 2024 by Bator Menyhert Koncz, Pal Szabo & Mona Dierickx'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ndveye class from file ndveye.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ndveye import ndveyePlugin
    return ndveyePlugin()
