# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ndveye
                                 A QGIS plugin
 Plant counting.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-25
        copyright            : (C) 2024 by Bator Menyhert Koncz, Pal Szabo & Mona Dierickx
        email                : ndveye@protonmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "Bator Menyhert Koncz, Pal Szabo & Mona Dierickx"
__date__ = "2024-03-25"
__copyright__ = "(C) 2024 by Bator Menyhert Koncz, Pal Szabo & Mona Dierickx"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

from qgis.PyQt.QtGui import QColor
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterMultipleLayers,
    QgsProcessingParameterNumber,
    QgsProcessingParameterBoolean,
    QgsProject,
    QgsVectorLayer,
    QgsSimpleLineSymbolLayer,
    QgsSimpleMarkerSymbolLayer,
    QgsProcessingParameterFolderDestination
)
import os
import shapely
import rasterio
import numpy as np
import pandas as pd
import geopandas as gpd
import astropy.convolution
import photutils.segmentation
import json

class ndveyeAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = "OUTPUT"
    INPUT = "INPUT"

    def add_param(self, param, help_text=None):
        if help_text:
            param.setHelp(help_text)
        self.addParameter(param)

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        self.add_param(
            QgsProcessingParameterMultipleLayers(
                "inputRasters",
                # accept any raster layers:
                self.tr("Input raster(s)"),
                QgsProcessing.TypeRaster,
            ),
            "The layer that will be analysed and where the plants will be counted by the algorithm. Consider preprocessing these layers by using spectral indeces, such as NDVI."
        )

        self.add_param(
            QgsProcessingParameterNumber(
                "Background offset",
                self.tr("Background offset"),
                QgsProcessingParameterNumber.Double,
                defaultValue=0.15,
                minValue=0.0,
                maxValue=0.9
            ),
            """
            This value will be subtracted from each pixel to make the true features stand out more. 
            In case of a brighter background (for example due to more weeds) a higher background offset will improve the algorithms' results. 
            Keep in mind that the background offset will be subtracted from the value of each pixel, meaning that a higher background offset will require a lower threshold.
            """
        )

        self.add_param(
            QgsProcessingParameterNumber(
                "Kernel FWHM",
                self.tr("Kernel FWHM"),
                QgsProcessingParameterNumber.Double,
                1.0,
            ),
            """
            The full-width at half-maximum (FWHM) of the 2D circular Gaussian kernel.
            This will determine the amount of smoothing that will happen, with a higher value increasing the smoothing and a smaller one decreasing it.
            If smaller plants are not being detected consider lowering the kernel FWHM, as a less wide kernel will erase less small objects.
            """
        )

        self.add_param(
            QgsProcessingParameterNumber(
                "Kernel size",
                self.tr("Kernel size"),
                QgsProcessingParameterNumber.Integer,
                7,
            ),
            """
            The size of the kernel along each axis, this must be an odd value.
            """
        )

        self.add_param(
            QgsProcessingParameterNumber(
                "Detection threshold",
                self.tr("Detection threshold"),
                QgsProcessingParameterNumber.Double,
                defaultValue=0.5,
                minValue=0.0,
                maxValue=10.0
            ),
            """
            The minimum value a pixel needs to have in order to be seen as part of an object that could be detected. Keep in mind that the background offset will be subtracted from the value of each pixel, meaning that a higher background offset will require a lower threshold. 
            To estimate, check the value of one of the object you mean to detect, subtract the background offset and use that as a starting point.
            """
        )

        self.add_param(
            QgsProcessingParameterNumber(
                "Minimum pixel count",
                self.tr("Minimum pixel count"),
                QgsProcessingParameterNumber.Integer,
                defaultValue=2,
                minValue=1
            ),
            """
            The minimum number of connected pixels, each greater than threshold, that an object must have to be detected.
            """
        )

        self.add_param(
            QgsProcessingParameterBoolean(
                "Connectivity: use 8 instead of 4",
                self.tr("Connectivity: use 8 instead of 4"),
                defaultValue=False,
            ),
            """
            The connectivity method that is used to determine the amount of pixels that make up an object. In case of 4-connectivity each pixel is only considered as connected to the pixels that touch along the edges, making each pixel connected to 4 other pixels. With 8-connectivity pixels that touch along the corneers are also considered as connected, making each pixel connected to 8 other pixels.
            By default 4-connectivity is used, if the algorithms' predictions exclude parts of the plant that are more elongated or distant from the core of the plant, consider using 8-connectivity instead.
            """
        )

        self.add_param(
            QgsProcessingParameterNumber(
                "Number of deblending thresholds",
                self.tr("Number of deblending thresholds"),
                QgsProcessingParameterNumber.Integer,
                500,
            ),
            """
            The number of multi-thresholding levels to use for deblending. A higher number of thresholds will allow for more peaks to be deblended into separate objects.
            """
        )

        self.add_param(
            QgsProcessingParameterNumber(
                "Minimum contrast for object separation",
                self.tr("Minimum contrast for object separation"),
                QgsProcessingParameterNumber.Double,
                defaultValue=0.05,
                minValue=0.0,
                maxValue=10.0
            ),
            """
            Determines the level of deblending that will happen. This value needs to be between zero and one, with zero causing every peak to be seen as a separate object and one not allowing any deblending causing every connected object to be seen as only one object.
            If the algoritmh has separated singular plants into several object, increase this value. If the algorithm has connected several plant into a singular object, decrease this value.
            """
        )

        self.add_param(
            QgsProcessingParameterBoolean(
                "Output: polygons",
                self.tr("Output: polygons"),
                defaultValue=True,
            ),
            "Determines whether or not a vector layer with the polygons of the detected plants will be generated. The polygons will be the smallest possible polygon that contains the plant."
        )

        self.add_param(
            QgsProcessingParameterBoolean(
                "Output: points",
                self.tr("Output: points"),
                defaultValue=True,
            ),
            "Determines whether or not a vector layer with the points of the detected plants will be generated. The points will be the center of each plant."
        )

        self.add_param(
            QgsProcessingParameterBoolean(
                "Output: summary",
                self.tr("Output: summary"),
                defaultValue=True,
            ),
            "Determines whether or not a json file with a summary of the parameters used for the analysis and the number of detected plants (per layer) will be generated."
        )
        
        self.add_param(
            QgsProcessingParameterFolderDestination(
                "Folder path",
                "Folder location"
            ),
            "The folder where the output files will be saved."
        )

    def processAlgorithm(self, parameters, context, feedback):
        folder_path = self.parameterAsString(parameters, 'Folder path', context)
        polygondfs = []
        pointdfs = []
        objectcount = {}
        totalcount = 0

        for index, inputId in enumerate(parameters["inputRasters"]):
            counter = 0
            for _, v in QgsProject.instance().mapLayers().items():
                if v.id() == inputId:
                    inputFile = v.source()
                    layer_crs = v.crs()
                    layer_crs_id = layer_crs.authid()
                    counter += 1
            assert counter < 2, "Multiple layers with the same id found"

            with rasterio.open(inputFile, "r") as src:
                data = src.read(1)
                profile = src.profile
                bounds = src.bounds

            rowNum, colNum = data.shape

            totalWidth = bounds.right - bounds.left
            totalHeight = bounds.top - bounds.bottom

            pixelWidth = totalWidth / colNum
            pixelHeight = totalHeight / rowNum

            def pixelcoord_to_epsg3857(row, col):
                x = bounds.left + (col + 1 / 2) * pixelWidth
                y = bounds.top - (row + 1 / 2) * pixelHeight
                return x, y

            def point_to_square(
                centerx, centery, pixelWidth=pixelWidth, pixelHeight=pixelHeight
            ):
                return shapely.geometry.Polygon(
                    [
                        [centerx - pixelWidth / 2, centery - pixelHeight / 2],
                        [centerx + pixelWidth / 2, centery - pixelHeight / 2],
                        [centerx + pixelWidth / 2, centery + pixelHeight / 2],
                        [centerx - pixelWidth / 2, centery + pixelHeight / 2],
                        [centerx - pixelWidth / 2, centery - pixelHeight / 2],
                    ]
                )

            # Apply background offset
            data -= np.ones(shape=data.shape) * parameters["Background offset"]

            kernel = photutils.segmentation.make_2dgaussian_kernel(
                parameters["Kernel FWHM"], size=parameters["Kernel size"]
            )
            convolved_data = astropy.convolution.convolve(data, kernel)

            segment_map = photutils.segmentation.detect_sources(
                convolved_data,
                np.ones(shape=data.shape) * parameters["Detection threshold"],
                npixels=parameters["Minimum pixel count"],
                connectivity=8 if parameters["Connectivity: use 8 instead of 4"] else 4,
            )

            segm_deblend = photutils.segmentation.deblend_sources(
                convolved_data,
                segment_map,
                npixels=parameters["Minimum pixel count"],
                nlevels=parameters["Number of deblending thresholds"],
                contrast=parameters["Minimum contrast for object separation"],
                progress_bar=True,
            )

            shapes = []
            for label in segm_deblend.labels:
                xs, ys = np.where(np.array(segm_deblend) == label)
                targetPixels = [[x, y] for (x, y) in zip(xs, ys)]
                targetPixelsArray = [point_to_square(*pixelcoord_to_epsg3857(*each)).buffer(0.001) for each in targetPixels]

                shapes.append(shapely.unary_union(targetPixelsArray))

            nr_detected_objects = len(shapes)
            objectcount[inputId] = nr_detected_objects
            totalcount += nr_detected_objects
            
            group = os.path.basename(inputFile).replace(".tif", "")

            geom = gpd.GeoSeries(shapes).set_crs(layer_crs_id)
            gdf = gpd.GeoDataFrame(geometry=geom)
            gdf["group"] = group
            polygondfs.append(gdf)

            geom = [each.centroid for each in shapes]
            gdf = gpd.GeoDataFrame(geometry=geom)
            gdf["group"] = group
            pointdfs.append(gdf)

        if parameters["Output: polygons"]:
            gpd.GeoDataFrame(pd.concat(polygondfs)).set_crs(layer_crs_id).to_file(
                folder_path + "/polygons.gpkg",
                driver="GPKG",
                layer="polygons",
                engine="pyogrio",
            )
            polygonLayer = QgsProject.instance().addMapLayer(
                QgsVectorLayer(
                    folder_path + "/polygons.gpkg", "resultPolygons", "ogr"
                )
            )
            polygonLayer.renderer().symbol().changeSymbolLayer(
                0, QgsSimpleLineSymbolLayer(QColor("#ebe134"), width=1)
            )

        if parameters["Output: points"]:
            gpd.GeoSeries(pd.concat([e.geometry for e in pointdfs])).set_crs(layer_crs_id).to_file(
                folder_path + "/points.gpkg",
                driver="GPKG",
                layer="points",
                engine="pyogrio",
                index=False,
            )
            pointsLayer = QgsProject.instance().addMapLayer(
                QgsVectorLayer(
                    folder_path + "/points.gpkg", "resultPoints", "ogr"
                )
            )
            pointsLayer.renderer().symbol().changeSymbolLayer(
                0, QgsSimpleMarkerSymbolLayer(color=QColor("#38db2c"), size=3)
            )

        data = {
            "Total objects detected": totalcount,
            "Objects per layer": objectcount,
            "CRS": layer_crs_id,
            "Background offset": parameters["Background offset"],
            "Input Parameters": parameters,
        }

        if parameters["Output: summary"]:
            output_file = folder_path + "/summary.json"
            with open(output_file, "w") as file:
                json.dump(data, file, indent=4)
        
        return data

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return "NDVeye"

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ""

    def tr(self, string):
        return QCoreApplication.translate("Processing", string)

    def createInstance(self):
        return ndveyeAlgorithm()
